name: ${name}
version: ${version}
description: ${description}
authors: [TheBlockBender, JustDJplease]
main: me.theblockbender.vocelshortcuts.Main
website: https://github.com/JustDJplease/VoxelShortcuts
database: false